<div id="particles-js"></div>
<div class="container register center">
    <h1 class="register-head">Registreren Bedrijf</h1>
    <hr>
    <?php if (!empty($vars['formMessage'])) : ?>
        <?= $vars['formMessage'] ?>
    <?php endif; ?>
    <form class="needs-validation register-bedrijf-form" action="" method="POST" novalidate>
        <!--Email row-->
        <div class="form-row">
            <div class="form-group col-12">
                <label for="email_bedrijf">E-mail:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-at"></i></div>
                    </div>
                    <input type="email" class="form-control" id="email_bedrijf" name="email"
                           placeholder="E-mail" required autofocus>
                    <div class="invalid-tooltip">Voer een geldig bedrijfsemail in!</div>
                </div>
                <span class="register-detail">
                    Voer een geldig bedrijfsemail in, na aanmelding wordt uw aanvraag gecontroleerd door een admin.
                    Dit kan maximaal een dag duren, vervolgens zult u een verificatie mail ontvangen.
                </span>
            </div>
        </div>
        <!--Wachtwoord row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-6">
                <label for="password_bedrijf">Wachtwoord:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                    </div>
                    <input type="password" class="form-control" id="password_bedrijf" name="password"
                           placeholder="Wachtwoord" minlength="8" required>
                    <div class="invalid-tooltip">Voer een wachtwoord in met tenminste 8 karakters, 1 cijfer en 1 hoofdletter!
                    </div>
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="fas fa-fw fa-eye toggle-password"></i></div>
                    </div>
                </div>
                <span class="register-detail">Het wachtwoord moet minstens 8 karakters lang zijn, 1 cijfer en 1 hoofdletter bevatten.</span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label for="password_bedrijf_check">Herhaal wachtwoord:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                    </div>
                    <input type="password" class="form-control" id="password_bedrijf_check" name="repeat_password"
                           placeholder="Wachtwoord" minlength="8" required>
                    <div class="invalid-tooltip">Herhaal het wachtwoord!</div>
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="fas fa-fw fa-eye toggle-password"></i></div>
                    </div>
                </div>
                <span class="register-detail">Herhaal het wachtwoord ter controle.</span>
            </div>
        </div>
        <!--Belasting row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-12">
                <label for="kvk_nummer">KvK-nummer:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-address-book"></i></div>
                    </div>
                    <input type="number" class="form-control" id="kvk_nummer" name="number"
                           placeholder="Bijvoorbeeld: 12345678:" minlength="8" max="99999999"
                           oninput="if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);"
                           maxlength="8" required>
                    <div class="invalid-tooltip">Voer uw KvK-nummer in!</div>
                </div>
                <span class="register-detail">Voer uw KvK-nummer in.</span>
            </div>
        </div>
        <!--Akkoord row-->
        <div class="form-row">
            <div class="form-group col-12">
                <div class="row no-gutters">
                    <!--Terms & Conditions-->
                    <div class="terms col-12 col-sm-6">
                        <div class="custom-control custom-checkbox mb-2">
                            <input type="checkbox" class="custom-control-input" id="akkoord_bedrijf" required>
                            <label class="custom-control-label" for="akkoord_bedrijf">Ik ga akkoord met de voorwaarden.</label>
                            <div class="invalid-tooltip">Ga akkoord met de voorwaarden!</div>
                        </div>
                    </div>
                    <!--reCAPTCHA-->
                    <div class="captcha col-12 col-sm-6">
                        <div class="g-recaptcha" data-sitekey="6LcB58YUAAAAAPegXRs_NuncFTfvfs-gPDiDyunC"></div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="hr-bottom">
        <!--Register button-->
        <div class="reg-btn-row">
            <button type="submit" class="btn reg-btn btn-primary" name="reg_submit">Registreer</button>
        </div>
        <!--Detail text-->
        <h6 class="reg-bedr">Of bent u zzp'er? Klik dan <a href="<?= $vars['baseUrl'] ?>register/zzp">hier</a>.</h6>
    </form>
</div>