<div id="particles-js"></div>
<div class="container register center">
    <h1 class="register-head">Registreren ZZP'er</h1>
    <hr>
    <form class="register-zzp-form" action="" method="POST">
        <!--Email row-->
        <div class="form-row">
            <div class="form-group col-12">
                <label for="email_reg_zzp">E-mail:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-at"></i></div>
                    </div>
                    <input type="email" class="form-control" id="email_reg_zzp" placeholder="E-mail" required autofocus>
                </div>
                <span class="register-detail">Voer een geldig email in, u krijgt een verificatie mail.</span>
            </div>
        </div>
        <!--Wachtwoord row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-6">
                <label for="wachtwoord_reg_zzp1">Wachtwoord:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                    </div>
                    <input type="password" class="form-control" id="wachtwoord_reg_zzp1" placeholder="Wachtwoord" minlength="8" required>
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="fas fa-fw fa-eye toggle-password"></i></div>
                    </div>
                </div>
                <span class="register-detail">Het wachtwoord moet minstens 8 karakters lang zijn en 1 hoofdletter bevatten.</span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label for="wachtwoord_reg_zzp2">Herhaal wachtwoord:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                    </div>
                    <input type="password" class="form-control" id="wachtwoord_reg_zzp2" placeholder="Wachtwoord" minlength="8" required>
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="fas fa-fw fa-eye toggle-password"></i></div>
                    </div>
                </div>
                <span class="register-detail">Herhaal het wachtwoord ter controle.</span>
            </div>
        </div>
        <!--Belasting row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-12">
                <label for="bnummer">Btw-identificatienummer:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-address-book"></i></div>
                    </div>
                    <input type="text" class="form-control" id="bnummer" placeholder="Bijvoorbeeld: NL-001234567-B34:" required>
                </div>
                <span class="register-detail">Voer uw btw-identificatienummer in.</span>
            </div>
        </div>
        <!--Akkoord row-->
        <div class="form-row">
            <div class="form-group col-12">
                <div class="row no-gutters">
                    <!--Terms & Conditions-->
                    <div class="terms col-12 col-sm-6">
                        <div class="custom-control custom-checkbox mb-2">
                            <input type="checkbox" class="custom-control-input" id="akkoord" required>
                            <label class="custom-control-label" for="akkoord">Ik ga akkoord met de voorwaarden.</label>
                            <div class="invalid-feedback">Je moet eerst akkoord gaan voor dat je verder kunt!</div>
                        </div>
                    </div>
                    <!--reCAPTCHA-->
                    <div class="captcha col-12 col-sm-6">
                        <div class="g-recaptcha" data-sitekey="6LcB58YUAAAAAPegXRs_NuncFTfvfs-gPDiDyunC"></div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="hr-bottom">
        <!--Register button-->
        <div class="reg-btn-row">
            <button type="submit" class="btn reg-btn btn-primary">Registreer</button>
        </div>
        <!--Detail text-->
        <h6 class="reg-bedr">Of bent u eigenaar van een bedrijf? Klik dan <a href="<?= $vars['baseUrl'] ?>register/bedrijf">hier</a>.</h6>
    </form>
</div>