<div id="particles-js"></div>
<div class="container register center">
    <h1 class="register-head">Registreren ZZP'er</h1>
    <hr>
    <?php if (!empty($vars['formMessage'])) : ?>
        <?= $vars['formMessage'] ?>
    <?php endif; ?>
    <form class="needs-validation register-zzp-form" action="" method="POST" novalidate>
        <!--Email row-->
        <div class="form-row">
            <div class="form-group col-12">
                <label for="email_zzp">E-mail:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-at"></i></div>
                    </div>
                    <input type="email" class="form-control" id="email_zzp" name="email"
                           placeholder="E-mail" required autofocus>
                    <div class="invalid-tooltip">Voer een geldig email in!</div>
                </div>
                <span class="register-detail">Voer een geldig email in, u krijgt een verificatie mail.</span>
            </div>
        </div>
        <!--Wachtwoord row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-6">
                <label for="password_zzp">Wachtwoord:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                    </div>
                    <input type="password" class="form-control" id="password_zzp" name="password"
                           placeholder="Wachtwoord" minlength="8" required>
                    <div class="invalid-tooltip">Voer een wachtwoord in met tenminste 8 karakters, 1 cijfer en 1 hoofdletter!
                    </div>
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="fas fa-fw fa-eye toggle-password"></i></div>
                    </div>
                </div>
                <span class="register-detail">Het wachtwoord moet minstens 8 karakters lang zijn, 1 cijfer en 1 hoofdletter bevatten.</span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label for="password_zzp_check">Herhaal wachtwoord:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                    </div>
                    <input type="password" class="form-control" id="password_zzp_check" name="repeat_password"
                           placeholder="Wachtwoord" minlength="8" required>
                    <div class="invalid-tooltip">Herhaal het wachtwoord!</div>
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="fas fa-fw fa-eye toggle-password"></i></div>
                    </div>
                </div>
                <span class="register-detail">Herhaal het wachtwoord ter controle.</span>
            </div>
        </div>
        <!--Belasting row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-12">
                <label for="btw_nummer">Btw-identificatienummer:</label><span class="required">*</span>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-address-book"></i></div>
                    </div>
                    <input type="text" class="form-control" id="btw_nummer" name="number"
                           placeholder="Bijvoorbeeld: NL-001234567-B34:" required>
                    <div class="invalid-tooltip">Voer uw Btw-identificatienummer in!</div>
                </div>
                <span class="register-detail">Voer uw btw-identificatienummer in.</span>
            </div>
        </div>
        <!--Akkoord row-->
        <div class="form-row">
            <div class="form-group col-12">
                <div class="row no-gutters">
                    <!--Terms & Conditions-->
                    <div class="terms col-12 col-sm-6">
                        <div class="custom-control custom-checkbox mb-2">
                            <input type="checkbox" class="custom-control-input" id="akkoord_zzp" required>
                            <label class="custom-control-label" for="akkoord_zzp">Ik ga akkoord met de voorwaarden.</label>
                            <div class="invalid-tooltip">Ga akkoord met de voorwaarden!</div>
                        </div>
                    </div>
                    <!--reCAPTCHA-->
                    <div class="captcha col-12 col-sm-6">
                        <div class="g-recaptcha" data-sitekey="6LcB58YUAAAAAPegXRs_NuncFTfvfs-gPDiDyunC"></div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="hr-bottom">
        <!--Register button-->
        <div class="reg-btn-row">
            <button type="submit" class="btn reg-btn btn-primary" name="reg_submit">Registreer</button>
        </div>
        <!--Detail text-->
        <h6 class="reg-bedr">Of bent u eigenaar van een bedrijf? Klik dan <a href="<?= $vars['baseUrl'] ?>register/bedrijf">hier</a>.</h6>
    </form>
</div>