<div class="container-fluid dash">
    <h1 class="dashboard-head normal">Admin Dashboard</h1>
    <hr>
    <div class="card-row">
        <div class="card card-dashboard">
            <h5 class="card-header">Gebruiker Beheer</h5>
            <div class="card-body">
                <div class="row">
                    <div class="card-icon-row col-4">
                        <i class="card-icon far fa-address-book"></i>
                    </div>
                    <div class="card-content col-8">
                        <div class="row">
                            <h6 class="card-text">Bekijk alle aangemelde gebruikers hier</h6>
                        </div>
                        <div class="card-btn-row row">
                            <a href="<?= $vars['baseUrl'] ?>profile/admin" class="btn btn-primary btn-block card-btn">Bekijk Beheer</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-dashboard">
            <h5 class="card-header">Opdrachten Beheer</h5>
            <div class="card-body">
                <div class="row">
                    <div class="card-icon-row col-4">
                        <i class="card-icon fas fa-archive"></i>
                    </div>
                    <div class="card-content col-8">
                        <div class="row">
                            <h6 class="card-text">Beheer hier alle opdrachten die zijn aangemaakt</h6>
                        </div>
                        <div class="card-btn-row row">
                            <a href="" class="btn btn-primary btn-block card-btn">Opdrachten</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-dashboard">
            <h5 class="card-header">Instellingen</h5>
            <div class="card-body">
                <div class="row">
                    <div class="card-icon-row col-4">
                        <i class="card-icon fas fa-cog"></i>
                    </div>
                    <div class="card-content col-8">
                        <div class="row">
                            <h6 class="card-text">Account instellingen, als wachtwoord veranderen.</h6>
                        </div>
                        <div class="card-btn-row row">
                            <a href="" class="btn btn-primary btn-block card-btn">Instellingen</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-dashboard">
            <h5 class="card-header">Database</h5>
            <div class="card-body">
                <div class="row">
                    <div class="card-icon-row col-4">
                        <i class="card-icon fas fa-database"></i>
                    </div>
                    <div class="card-content col-8">
                        <div class="row">
                            <h6 class="card-text">Bekijk de database van CapitalZ op PhPmyAdmin.</h6>
                        </div>
                        <div class="card-btn-row row">
                            <a href="" class="btn btn-primary btn-block card-btn">Database</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>