<div class="container-fluid dash">
    <h1 class="dashboard-head">Zzp Dashboard</h1>
    <hr>
    <div class="card-row">
        <div class="card card-dashboard">
            <h5 class="card-header">Profiel</h5>
            <div class="card-body">
                <div class="row">
                    <div class="card-icon-row col-4">
                        <i class="card-icon fas fa-user"></i>
                    </div>
                    <div class="card-content col-8">
                        <div class="row">
                            <h6 class="card-text">Bekijk hier uw profiel en pas deze aan.</h6>
                        </div>
                        <div class="card-btn-row row">
                            <a href="<?= $vars['baseUrl'] ?>profile/zzp" class="btn btn-primary btn-block card-btn">Mijn profiel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-dashboard">
            <h5 class="card-header">Opdrachten</h5>
            <div class="card-body">
                <div class="row">
                    <div class="card-icon-row col-4">
                        <i class="card-icon fas fa-clipboard-list"></i>
                    </div>
                    <div class="card-content col-8">
                        <div class="row">
                            <h6 class="card-text">Bekijk jouw huidige en oude opdrachten hier.</h6>
                        </div>
                        <div class="card-btn-row row">
                            <a href="<?= $vars['baseUrl'] ?>task-zzp" class="btn btn-primary btn-block card-btn">Mijn opdrachten</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-dashboard">
            <h5 class="card-header">Instellingen</h5>
            <div class="card-body">
                <div class="row">
                    <div class="card-icon-row col-4">
                        <i class="card-icon fas fa-cog"></i>
                    </div>
                    <div class="card-content col-8">
                        <div class="row">
                            <h6 class="card-text">Account instellingen, als wachtwoord veranderen.</h6>
                        </div>
                        <div class="card-btn-row row">
                            <a href="<?= $vars['baseUrl'] ?>settings/zzp" class="btn btn-primary btn-block card-btn">Instellingen</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>