<!-- Set CSS files -->
<link rel="stylesheet" href="<?= $this->url('style/css/bootstrap.min.css') ?>">

<!-- Fonts -->
<link rel="stylesheet" href="<?= $this->url('font/font.css') ?>">

<!-- Compiled SCSS file import -->
<link rel="stylesheet" href="<?= $this->url('style/css/main.css') ?>">

<!-- Extra CSS files -->
<link rel="stylesheet" href="<?= $this->url('style/css/hamburgers.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/dark-mode.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/particles.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/cookiealert.css') ?>">

<!--Icon CSS files-->
<link rel="stylesheet" href="<?= $this->url('style/css/fontawesome.min.css') ?>">

<?php if (empty($this->urlArr['pagename'])) $this->urlArr['pagename'] = 'home'; ?>