<!-- Set CSS files -->
<link rel="stylesheet" href="<?= $this->urlArr['baseUrl'] ?>/css/bootstrap.css">

<!-- Fonts -->
<link rel="stylesheet" href="<?= $this->urlArr['baseUrl'] ?>/font/font.css">

<!-- Custom CSS files -->
<link rel="stylesheet" href="<?= $this->urlArr['baseUrl'] ?>/css/style.css">
<link rel="stylesheet" href="<?= $this->urlArr['baseUrl'] ?>/css/hamburgers.css">
<link rel="stylesheet" href="<?= $this->urlArr['baseUrl'] ?>/css/navbar.css">
<link rel="stylesheet" href="<?= $this->urlArr['baseUrl'] ?>/css/footer.css">
<link rel="stylesheet" href="<?= $this->urlArr['baseUrl'] ?>/css/dark-mode.css">