</section>
</main>
<!--Footer-->
<footer class="footer">
    <div class="dark-mode-switch">
        <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="darkSwitch">
            <label class="custom-control-label" for="darkSwitch"><i class="fas" id="toggle-icon"></i></label>
        </div>
    </div>

    <div class="footer-copyright">
        <div class="text-center">© 2019 Copyright:<a href="<?= $this->urlArr['baseUrl'] ?>home"> CapitalZ</a></div>
    </div>
</footer>

<!-- START Bootstrap-Cookie-Alert -->
<div class="alert text-center cookiealert" role="alert">
    <b>Wij gebruiken cookies &#x1F36A; op onze site om u de beste gebruikers ervaring te leveren.</b>
    <a href="https://cookiesandyou.com/" target="_blank"> Klik hier</a> om meer over cookies te lezen.
    <button type="button" class="btn btn-primary btn-sm acceptcookies">Akkoord</button>
</div>

<!-- Include the needed scripts. -->
<?php $this->get_part('js'); ?>
</body>
</html>