</section>
</main>
<!--Footer-->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-copyright col-12">
                <div class="text-center">© 2019 Copyright:<a href="<?= $this->urlArr['baseUrl'] ?>home"> CapitalZ</a></div>
            </div>
        </div>
    </div>
</footer>
<!-- Include the needed scripts. -->
<?php $this->get_part('js'); ?>
</body>
</html>