</section>
</main>
<!--Footer-->
<footer class="footer">
    <div class="dark-mode-switch">
        <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="darkSwitch">
            <label class="custom-control-label" for="darkSwitch"><i class="fas fa-sun"></i></label>
        </div>
    </div>

    <div class="footer-copyright">
        <div class="text-center">© 2019 Copyright:<a href="<?= $this->urlArr['baseUrl'] ?>home"> CapitalZ</a></div>
    </div>
</footer>

<!-- Include the needed scripts. -->
<?php $this->get_part('js'); ?>
</body>
</html>