<!-- Java script files, JQuery, Popper, Bootstrap. -->
<script src="<?= $this->url('js/jquery-3.4.1.min.js') ?>"></script>
<script src="<?= $this->url('js/popper.min.js') ?>"></script>
<script src="<?= $this->url('js/bootstrap.min.js') ?>"></script>

<!-- Custom Java script files -->
<script src="<?= $this->url('js/particles.js') ?>"></script>
<script src="<?= $this->url('js/darkmode.js') ?>"></script>
<script src="<?= $this->url('js/imask.js') ?>"></script>

<!--Icons Java script files-->
<script src="<?= $this->url('js/icons/fontawesome.min.js') ?>"></script>
<script src="<?= $this->url('js/icons/regular.min.js') ?>"></script>
<script src="<?= $this->url('js/icons/solid.min.js') ?>"></script>

<!--reCAPTCHA-->
<script src="https://www.google.com/recaptcha/api.js" async defer></script>

<!--JS file-->
<script src="<?= $this->url('js/main.js') ?>"></script>