<!-- Java script files, JQuery, Popper, Bootstrap. -->
<script src="<?= $this->urlArr['baseUrl'] ?>/js/jquery-3.4.1.js"></script>
<script src="<?= $this->urlArr['baseUrl'] ?>/js/popper.js"></script>
<script src="<?= $this->urlArr['baseUrl'] ?>/js/bootstrap.js"></script>

<!--reCAPTCHA-->
<script src="<?= $this->urlArr['baseUrl'] ?>/js/api.js" async defer></script>

<!-- Custom Java script files -->
<script src="<?= $this->urlArr['baseUrl'] ?>/js/particles.js"></script>
<script src="<?= $this->urlArr['baseUrl'] ?>/js/cookiealert.js"></script>
<script src="<?= $this->urlArr['baseUrl'] ?>/js/icons.js"></script>
<script src="<?= $this->urlArr['baseUrl'] ?>/js/dark-mode-switch.js"></script>

<script src="<?= $this->urlArr['baseUrl'] ?>/js/script.js"></script>