<!-- Char set -->
<meta charset="UTF-8">

<!-- Keywords -->
<meta name="keywords" content="HTML, SCSS, CSS, PHP, JavaScript, JQuery">

<!-- Author -->
<meta name="author" content="CapitalZ">

<!-- Description -->
<meta name="description" content="CapitalZ is een site waar ZZP'ers en bedrijven elkaar kunnen vinden.">

<!-- Theme color: Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#4386F3">
<meta name="apple-mobile-web-app-status-bar-style" content="#4386F3">

<!-- Theme color: Windows Phone -->
<meta name="msapplication-navbutton-color" content="#4386F3">

<!-- Theme color: iOS Safari -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="blue">

<!-- Viewport configuration -->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Compatibility -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<!-- Vertaal de site niet met google -->
<meta name="google" content="notranslate">