<nav class="navbar navbar-expand-lg navbar-expand-md navbar-light">
    <a href="<?= $this->urlArr['baseUrl'] ?>">
        <div class="logo">
            <?= $this->svg_helper("logo"); ?>
        </div>
    </a>
    <button class="navbar-toggler hamburger hamburger--squeeze" type="button" data-toggle="collapse" data-target="#nav-collapse">
        <span class="hamburger-box">
            <span class="hamburger-inner"></span>
        </span>
    </button>
    <div class="collapse navbar-collapse" id="nav-collapse">
        <ul class="navbar-nav ml-auto">

            <?php

            if (!empty($_SESSION["user_role"])) {
                switch ($_SESSION["user_role"]) {
                    case '0':
                        echo '<li class="nav-item"><a class="nav-link" href="http://localhost/phpmyadmin/db_structure.php?server=1&db=capitalz_db" target="_blank"><i class="fas fa-database"></i> <span class="mobile">Database</span></a></li>';
                        break;
                    case '1':
                        echo '<li class="nav-item"><a class="nav-btn nav-link" href=" "><button class="btn btn-primary"><i class="fas fa-plus"></i> Maak Opdracht</button></a></li>';
                        echo '<li class="nav-item dropdown"><a class="profile-link nav-link" href="" id="navbarDropdown" role="button" data-toggle="dropdown"><img class="profile-img-link" src="../../img/profile.png" alt="pf link"></a><div class="dropdown-menu"><a class="dropdown-item" href=" ' . $this->urlArr['baseUrl'] . 'profile/bedrijf ">Profiel</a><div class="dropdown-divider"></div><a class="dropdown-item" href=" ' . $this->urlArr['baseUrl'] . ' ">Mijn Opdracten</a></div></li>';
                        break;
                    case '2':
                        echo '<li class="nav-item"><a class="nav-link" href=" "><i class="fas fa-receipt"></i> Mijn Opdrachten</a></li>';
                        echo '<li class="nav-item dropdown"><a class="profile-link nav-link" href="" id="navbarDropdown" role="button" data-toggle="dropdown"><img class="profile-img-link" src="../../img/profile.png" alt="pf link"></a><div class="dropdown-menu"><a class="dropdown-item" href=" ' . $this->urlArr['baseUrl'] . 'profile/zzp ">Profiel</a><div class="dropdown-divider"></div><a class="dropdown-item" href=" ' . $this->urlArr['baseUrl'] . ' ">Mijn Opdracten</a></div></li>';
                        break;
                    default:
                        header("Refresh: 1; url=" . $this->urlArr['baseUrl'] . "home");
                        break;
                }
                echo '<li class="nav-item"><a class="nav-link" href=" ' . $this->urlArr['baseUrl'] . 'logout"><i class="fas fa-sign-out-alt"></i> Uitloggen</a></li>';
            } else {
                echo '<li class="nav-item"><a class="nav-link" href=" ' . $this->urlArr['baseUrl'] . 'login"><i class="fas fa-sign-in-alt"></i> Log in</a></li>';
                echo '<li class="nav-item"><a class="nav-btn nav-link" href="' . $this->urlArr['baseUrl'] . 'register/zzp"><button class="btn btn-primary"><i class="fas fa-user-plus"></i> Registreer</button></a></li>';
            }
            ?>

        </ul>
    </div>
</nav>