<nav class="navbar navbar-expand-lg navbar-expand-md navbar-light">
    <a href="<?= $this->urlArr['baseUrl'] ?>">
        <div class="logo">
            <?= $this->svg_helper("logo"); ?>
        </div>
    </a>
    <button class="navbar-toggler hamburger hamburger--squeeze" type="button" data-toggle="collapse" data-target="#nav-collapse">
        <span class="hamburger-box">
            <span class="hamburger-inner"></span>
        </span>
    </button>
    <div class="collapse navbar-collapse" id="nav-collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="<?= $this->urlArr['baseUrl'] ?>login"><i class="fas fa-sign-in-alt"></i> Log in</a>
            </li>
            <li class="nav-item">
                <a href="<?= $this->urlArr['baseUrl'] ?>register/zzp">
                    <button class="btn btn-primary"><i class="fas fa-user-plus"></i> Registreer</button>
                </a>
            </li>
        </ul>
    </div>
</nav>