<form action="" method="POST">
    <div class="form-group">
        <label for="exampleFormControlInput1">Naam</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name" name="name">
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Date of Birth</label>
        <input type="date" class="form-control" id="exampleFormControlInput1" placeholder="je geboorte datum kech"
               name="birthday">
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Geslacht</label>
        <select class="form-control" id="exampleFormControlSelect1" name="gender">
            <option value="m">Man</option>
            <option value="f">Vrouw</option>
            <option value="o">Overig</option>
        </select>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Nationaliteit</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com"
               name="nationality">
    </div>
    <!--Submit button-->
    <div class="login-btn-row">
        <button type="submit" class="btn btn-block btn-primary" name="profile_submit">Submit</button>
    </div>
</form>

