<div class="container profile">
    <h1 class="profile-head-text">Profiel Bedrijf</h1>
    <hr>
    <div class="row profile-head">
        <div class="col-12 col-sm-4 pf-row">
            <img class="pro-pic" src="<?= $vars['baseUrl'] . 'img/' . UserController::get_profile_picture($_SESSION['id'], $_SESSION['user_role']) ?>" alt="pf">
        </div>
        <div class="col-12 col-sm-8 pro-head-body">
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Naam:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?= $company_name ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Email:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?= $email ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Land:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?= $state ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Stad:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?= $city ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>KvK-Nr:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?= $kvk_number ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Website:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?= $website ?></h5>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="profile-body">
        <h4>Over:</h4>
        <p><?= $about ?></p>
        <h4>Locatie:</h4>
        <div class="profile-loctation">
            <iframe width="500" height="500" id="profile-map" src="https://maps.google.com/maps?q=bakker%20bart%20utrecht&t=&z=13&ie=UTF8&iwloc=&output=embed"></iframe>
        </div>
    </div>
</div>

