<div class="container profile">
    <h1 class="profile-head-text normal">Profiel Zzp'er</h1>
    <hr>
    <div class="row profile-head">
        <div class="col-12 col-sm-4 pf-row">
            <img class="pro-pic" src="../../../img/profile.png" alt="pf">
        </div>
        <div class="col-12 col-sm-8 pro-head-body">
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Naam:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text">Henk van Kaas</h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Email:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text">henk@mail.nl</h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Geboortedatum:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text">9-11-2001</h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Geslacht:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text">Man</h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Nationaliteit:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text">Nederlands</h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Btw-Nr:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text">NL-36124585-B21</h5>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="profile-body">
        <h4>Over:</h4>
        <p>Mijn naam is Henk en ben 18 jaar, ik ben goed in webdevolpment en om precies te zijn back-end. Heb 2 jaar ervaring met PHP en 1 jaar met JS.</p>
        <h4>Diploma's:</h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Opleiding</th>
                <th scope="col">School</th>
                <th scope="col">Status</th>
            </tr>
            </thead>
            <tbody class="table-bordered">
            <tr>
                <td>HAVO</td>
                <td>SchoolSchool</td>
                <td class="table-success"><i class="fas fa-check"></i> Behaald</td>
            </tr>
            <tr>
                <td>HBO</td>
                <td>HogeSchoolSchool</td>
                <td class="table-warning"><i class="far fa-clock"></i> Bezig</td>
            </tr>
            </tbody>
        </table>
        <h4>Werkervaring:</h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Bedrijf</th>
                <th scope="col">Functie</th>
                <th scope="col">Tijd</th>
            </tr>
            </thead>
            <tbody class="table-bordered">
            <tr>
                <td>BerdrijfWerk</td>
                <td>Werk</td>
                <td>2014 - 2018</td>
            </tr>
            <tr>
                <td>WerkBedrijf</td>
                <td>Dingen</td>
                <td>2018 - Huidig</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

