<div class="container profile">
    <h1 class="profile-head-text">Profiel Zzp'er</h1>
    <hr>
    <div class="row profile-head">
        <div class="col-12 col-sm-4 pf-row">
            <img class="pro-pic" src="<?= $vars['baseUrl'] . 'img/' . UserController::get_profile_picture($_SESSION['id'], $_SESSION['user_role']) ?>" alt="pf">
        </div>
        <div class="col-12 col-sm-8 pro-head-body">
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Naam:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?php
                        $user_id = ApplicationController::sanitize($_SESSION['id']);
                        $db = new Database();
                        $db->query('SELECT firstname, infix, lastname FROM profile_se WHERE user_id = :user_id');
                        $db->bind(':user_id', $user_id);
                        $firstname = $db->single()['firstname'];
                        $infix = $db->single()['infix'];
                        $lastname = $db->single()['lastname'];

                        $fullname = $firstname . ' ' . $infix . ' ' . $lastname;
                        echo $fullname;
                        ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Email:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?php
                        $user_id = ApplicationController::sanitize($_SESSION['id']);
                        $db = new Database();
                        $db->query('SELECT email FROM `user` WHERE user_id = :user_id');
                        $db->bind(':user_id', $user_id);
                        $email = $db->single()['email'];
                        echo $email;
                        ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Geboortedatum:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?php
                        $user_id = ApplicationController::sanitize($_SESSION['id']);
                        $db = new Database();
                        $db->query('SELECT birthday FROM profile_se WHERE user_id = :user_id');
                        $db->bind(':user_id', $user_id);
                        $birthday = $db->single()['birthday'];
                        echo $birthday;
                        ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Geslacht:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?php
                        $user_id = ApplicationController::sanitize($_SESSION['id']);
                        $db = new Database();
                        $db->query('SELECT gender FROM profile_se WHERE user_id = :user_id');
                        $db->bind(':user_id', $user_id);
                        $gender = $db->single()['gender'];
                        echo $gender;
                        ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Nationaliteit:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?php
                        $user_id = ApplicationController::sanitize($_SESSION['id']);
                        $db = new Database();
                        $db->query('SELECT nationality FROM profile_se WHERE user_id = :user_id');
                        $db->bind(':user_id', $user_id);
                        $nationality = $db->single()['nationality'];
                        echo $nationality;
                        ?></h5>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-6">
                    <h5>Btw-Nr:</h5>
                </div>
                <div class="col-6">
                    <h5 class="pro-head-text"><?php
                        $user_id = ApplicationController::sanitize($_SESSION['id']);
                        $db = new Database();
                        $db->query('SELECT number FROM `user` WHERE user_id = :user_id');
                        $db->bind(':user_id', $user_id);
                        $number = $db->single()['number'];
                        echo $number;
                        ?></h5>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="profile-body">
        <h4>Over:</h4>
        <p><?php
            $user_id = ApplicationController::sanitize($_SESSION['id']);
            $db = new Database();
            $db->query('SELECT about FROM `profile_se` WHERE user_id = :user_id');
            $db->bind(':user_id', $user_id);
            $about = $db->single()['about'];
            echo $about;
            ?></p>
        <h4>CV:</h4>
    </div>
    <!--Edit button-->
    <hr>
    <?php
    if (isset($_SESSION["user_role"])) {
        switch ($_SESSION["user_role"]) {
            case '2':
                echo '
                    <div class="profile-btn-row">
                        <a href=" ' . $vars['baseUrl'] . 'profile_edit/zzp">
                            <button class="btn profile-btn btn-primary">Profiel Bewerken</button>
                        </a>
                    </div>
                ';
                break;
            default:
                break;
        }
    }
    ?>
</div>