<div class="container about">
    <h1 class="about-head ">Over ons</h1>
    <hr>
    <div class="row about-row">
        <div class="col-12 col-md-8">
            <div class="about-body">
                <h4 class="about-text-head">CapitalZ</h4>
                <h6 class="about-text">CaptitalZ is een bedrijf wat bedrijven en ZZP'ers in contact brengt.</h6>
                <hr>
                <h4 class="about-text-head">Wat wij leveren</h4>
                <h6 class="about-text">Hier bij CapitalZ geven we bedrijven de optie om opdrachten aan te bieden aan ZZP'ers, erkende bedrijven met een KvK nummer kunnen opdrachten aanbieden. ZZP'ers kunnen zich aanmelden voor opdrachten en vervolgens een opdracht uitvoeren voor de bedrijven. ZZP'ers krijgen betaald aan de hand van een vast gesteld bedrag en aan de eind krijgen ze een factuur van de
                    opdracht.</h6>
                <hr>
                <h4 class="about-text-head">Oprichting</h4>
                <h6 class="about-text">CapitalZ is gestart in 2016 en heeft vanaf 2019 ook een website. CapitalZ is in 2016 gestart door Willem van Ré.</h6>
                <hr>
                <h4 class="about-text-head">Het Bedrijf</h4>
                <h6 class="about-text">CapitalZ werkt met een team van 110 personen in hartje Amsterdam. Er is gekozen voor deze locatie voor zijn potentie in berijkbaarheid en ruimtelijke werkplek.</h6>
                <div class="about-image-row row no-gutters">
                    <img class="about-img-l col-12 col-sm-6" src="../img/capitalz_voor.png" alt="voor">
                    <img class="about-img-r col-12 col-sm-6" src="../img/capitalz_werk.png" alt="werk">
                </div>
                <hr>
                <div class="row">
                    <div class="col-12 col-md-5">
                        <div class="about-contact">
                            <h4 class="about-text-head">Locatie</h4>
                            <h6 class="about-info-head"><a href="https://goo.gl/maps/64hnnKpfZGmtqt5x6" target="_blank">Nieuwezijds Voorburgwal 104-108</a></h6>
                            <h6 class="about-info-head">1012 SG, Amsterdam</h6>
                            <h6 class="about-info-head">Nederland</h6>
                            <hr>
                            <h4 class="about-text-head">Contact</h4>
                            <h6 class="about-info-head"><a href="mailto:info@CapitalZ.nl" class="mail" target="_blank">info@CapitalZ.nl</a></h6>
                            <!--<h6 class="about-info-head"><a href="tel:" class="tel"></a></h6>-->
                        </div>
                    </div>
                    <div class="col-12 col-md-7">
                        <iframe width="100%" height="250" id="gmap_canvas" src="https://maps.google.com/maps?q=Nieuwezijds%20Voorburgwal%20104-108&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="about-info">
                <div class="about-img-info"><?= $this->svg_helper("icon"); ?></div>
                <h3 class="about-info-title text-center">CapitalZ.net</h3>
                <hr>
                <h4 class="about-info-head">Eigenaar:</h4>
                <h5 class="about-info-text">Willem van Ré</h5>
                <hr>
                <h4 class="about-info-head">Project Leider:</h4>
                <h5 class="about-info-text">Wob Jelsma</h5>
                <h4 class="about-info-head">Front-end:</h4>
                <h5 class="about-info-text">Iwan van der Wal</h5>
                <h4 class="about-info-head">Backend:</h4>
                <h5 class="about-info-text">Wob Jelsma</h5>
                <h5 class="about-info-text">Iwan van der Wal</h5>
                <h5 class="about-info-text">Robin van den Hoeven</h5>
            </div>
        </div>
    </div>
</div>