<div class="container about center">
    <h1 class="about-head ">Over ons</h1>
    <hr>

    <div class="container about-body">
        <p>
            Hier bij CapitalZ geven we bedrijven de optie om in contact te komen met ZZP'ers, erkende bedrijven met een KvK nummer kunnen opdrachten aanbieden aan ZZP'ers.
            ZZP'ers kunnen zich aanmelden voor opdrachten en vervolgens een opdracht uitvoeren voor de bedrijven.
            Achteraf kunnen de bedrijven en ZZP'ers een recensie schrijven over hoe de opdracht is gegaan.
            CapitalZ is gestart in 2016 en heeft vanaf 2019 ook een website. CapitalZ is in 2016 gestart door Willem van Ré.
        </p>
    </div>

</div>