<div class="container create">
    <h1 class="create-head">Taak Aanmaken</h1>
    <hr>
    <?php if (!empty($this->pageObj->formMessage)) : ?>
        <?= $this->pageObj->formMessage ?>
    <?php endif; ?>
    <form class="create-form" action="" method="POST">
        <!--Title row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-6">
                <label class="create-title" for="titel">Titel:</label>
                <input type="text" class="form-control" id="titel" name="title" placeholder="Taak titel:" required
                       autofocus
                       maxlength="20">
                <span class="create-detail">Een korte maar duidelijke titel voor de opdracht.</span>
            </div>
            <div class="form-group create-group col-6 col-md-3">
                <label class="create-title" for="tag">Tag:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-tag"></i></div>
                    </div>
                    <input type="text" class="form-control" id="tag" name="tag" value="Webdev" maxlength="10">
                </div>
            </div>
            <div class="form-group create-group col-6 col-md-3">
                <label class="create-title" for="bedrijf">Bedrijf:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="far fa-building"></i></div>
                    </div>
                    <input type="text" class="form-control" id="bedrijf" value="<?= $this->pageObj->company_name ?>" readonly>
                </div>
            </div>
        </div>
        <!--Info row-->
        <div class="form-row no-gutters">
            <div class="form-group col-12">
                <label class="create-title" for="desc">Beschrijving:</label>
                <textarea class="form-control" id="desc" name="desc" rows="5"></textarea>
            </div>
        </div>
        <!--Date and Sal row-->
        <div class="form-row">
            <div class="form-group col-12 col-md-6">
                <div class="form-row">
                    <div class="form-group col-12 col-sm-6">
                        <label class="create-title" for="date-start">Datum Begin:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="far fa-calendar-alt"></i></div>
                            </div>
                            <input type="date" class="form-control" value="<?php echo date('Y-m-d'); ?>"
                                   id="date-start" name="date_start">
                        </div>
                        <span class="create-detail">Begin datum van opdracht</span>
                    </div>
                    <div class="form-group col-12 col-sm-6">
                        <label class="create-title" for="date-end">Datum Eind:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="far fa-calendar-check"></i></div>
                            </div>
                            <input type="date" class="form-control"
                                   value="<?php echo date('Y-m-d', strtotime(' + 7 days')); ?>" id="date-end"
                                   name="date_end">
                        </div>
                        <span class="create-detail">Eind datum van opdracht.</span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-12 col-sm-6">
                        <label class="create-title" for="work_hours">Aantal Uren:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="far fa-clock"></i></div>
                            </div>
                            <input type="number" class="form-control" id="work_hours" name="work_hours" min="1" max="500" value="0">
                        </div>
                        <span class="create-detail">Maximaal 500 uur</span>
                    </div>
                    <div class="form-group col-12 col-sm-6">
                        <label class="create-title" for="work_sal">Uur Salaris:</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">€</div>
                            </div>
                            <input type="number" class="form-control" id="work_sal" name="work_sal" min="5" max="30" value="5">
                        </div>
                        <span class="create-detail">Tussen de €5 en €30 per uur.</span>
                    </div>
                </div>
            </div>
            <!--Image row-->
            <div class="form-group create-group col-12 col-md-6">
                <label class="create-title" for="image">Afbeelding:</label>
                <div id="image_select" class="create-image carousel slide" data-ride="carousel" data-interval="false">
                    <ol class="carousel-indicators">
                        <li data-target="#image_select" data-slide-to="0" class="active"></li>
                        <li data-target="#image_select" data-slide-to="1"></li>
                        <li data-target="#image_select" data-slide-to="2"></li>
                        <li data-target="#image_select" data-slide-to="3"></li>
                        <li data-target="#image_select" data-slide-to="4"></li>
                        <li data-target="#image_select" data-slide-to="5"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="../img/task-img/administration.jpg" class="d-block w-100" alt="img1">
                        </div>
                        <div class="carousel-item">
                            <img src="../img/task-img/cleaner.jpg" class="d-block w-100" alt="img2">
                        </div>
                        <div class="carousel-item">
                            <img src="../img/task-img/coding.jpg" class="d-block w-100" alt="img3">
                        </div>
                        <div class="carousel-item">
                            <img src="../img/task-img/garden.jpg" class="d-block w-100" alt="img4">
                        </div>
                        <div class="carousel-item">
                            <img src="../img/task-img/office.jpg" class="d-block w-100" alt="img5">
                        </div>
                        <div class="carousel-item">
                            <img src="../img/task-img/school.jpg" class="d-block w-100" alt="img6">
                        </div>
                        <div class="carousel-check center">
                            <i class="fas fa-5x fa-check"></i>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#image_select" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#image_select" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <!--Done button-->
        <hr class="hr-bottom">
        <div class="create-btn-row">
            <button type="submit" class="btn create-btn btn-primary" name="create_submit">Taak Uploaden</button>
        </div>
    </form>
</div>


