<div class="container forgot center">
    <h1 class="forgot-head ">Wachtwoord Vergeten</h1>
    <hr>
    <form class="forgot-form" method="post" action="">
        <!--Details row-->
        <div class="form-group">
            <h6 class="forgot-detail text-center">Als u uw wachtwoord bent vergeten zal deze moeten worden gereset. Doe dit door hieronder uw email te geven, u zal dan een mail ontvangen met een link naar de pagina waar u uw wachtwoord kunt resetten.</h6>
        </div>
        <!--Email row-->
        <div class="form-row">
            <div class="form-group col-12">
                <label for="email_forgot">E-mail:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-at"></i></div>
                    </div>
                    <input type="email" class="form-control" id="email_forgot" name="email_forgot" placeholder="E-mail" required autofocus>
                </div>
                <span class="forgot-detail">Wachtwoord vergeten? Klik <a href="<?= $this->urlArr['baseUrl'] ?>forgotpassword">hier</a>.</span>
            </div>
        </div>
        <!--Akkoord row-->
        <div class="form-group">
            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="akkoord_forgot" required>
                <label class="custom-control-label" for="akkoord_forgot">Ik ga akkoord met de voorwaarden.</label>
            </div>
        </div>
        <!--forgot button-->
        <hr class="hr-bottom">
        <div class="forgot-btn-row">
            <button type="submit" class="btn forgot-btn btn-primary ">Verstuur</button>
        </div>
    </form>
</div>