<div id="particles-js"></div>
<div class="container home center invis">
    <h1 class="home-head normal">Welkom bij CapitalZ!</h1>
    <h5 class="home-text normal">Dé site voor bedrijven en zpp'ers!</h5>
    <hr>
    <form method="post" action="<?= $this->urlArr['baseUrl'] ?>task">
        <div class="form-row home-form">
            <!--Wat invoer-->
            <div class="col-8 col-sm-7">
                <input type="text" class="form-control mb-2 normal" id="zoek" placeholder="Zoek opdrachten:">
            </div>
            <!--Plaats invoer-->
            <div class="col-4 col-sm-3">
                <select class="custom-select mb-2 mr-sm-2 normal" id="locatie">
                    <option selected disabled>Waar:</option>
                    <option value="1">Drenthe</option>
                    <option value="2">Flevoland</option>
                    <option value="3">Friesland</option>
                    <option value="4">Gelderland</option>
                    <option value="5">Groningen</option>
                    <option value="6">Limburg</option>
                    <option value="7">Noord-Brabant</option>
                    <option value="8">Noord-Holland</option>
                    <option value="9">Overrijsel</option>
                    <option value="10">Utrecht</option>
                    <option value="11">Zeeland</option>
                    <option value="12">Zuid-Holland</option>
                </select>
            </div>
            <!--Zoek button-->
            <div class="col-12 col-sm-2">
                <button type="submit" class="btn btn-block btn-primary mb-2 normal">Zoeken</button>
            </div>
        </div>
    </form>
    <h6 class="home-detail normal">Bent u eigenaar van een bedrijf? En wilt u uw opdracht plaatsen? Klik dan <a href="<?= $this->urlArr['baseUrl'] ?>register/bedrijf"><u>hier</u></a>!</h6>
</div>