<div class="container login center">
    <h1 class="login-head normal ">Login Zzp'er</h1>
    <hr>
    <form>
        <!--Email row-->
        <div class="form-row">
            <div class="form-group col-12">
                <label class="normal" for="email">E-mail:</label>
                <div class="normal input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-at"></i></div>
                    </div>
                    <input type="email" class="form-control" id="email" placeholder="E-mail">
                </div>
            </div>
        </div>
        <!--Wachtwoord row-->
        <div class="form-row">
            <div class="form-group col-12">
                <label class="normal" for="wachtwoord">Wachtwoord:</label>
                <div class="normal input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-key"></i></div>
                    </div>
                    <input type="password" class="form-control" id="wachtwoord_login" placeholder="Wachtwoord">
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="fas fa-fw fa-eye toggle-password"></i></div>
                    </div>
                </div>
                <span class="normal login-detail">Wachtwoord vergeten? Klik <a href="">hier</a>.</span>
            </div>
        </div>
        <!--Login button-->
        <hr class="hr-bottom">
        <div class="login-btn-row">
            <button type="submit" class="btn login-btn btn-primary normal ">Log in</button>
        </div>
        <h6 class="normal login-reg">Heeft u nog geen account? Klik dan <a href="<?= $this->urlArr['baseUrl'] ?>register/zzp">hier</a>.</h6>
    </form>
</div>