<?php if (isset($this->pageObj->zzpForm)) : ?>
    <div class="zzp-form">
        <?= $this->pageObj->zzpForm ?>
    </div>
<?php elseif (isset($this->pageObj->bedrijfForm)) : ?>
    <div class="bedrijf-form">
        <?= $this->pageObj->bedrijfForm ?>
    </div>
<?php else : ?>
    <?php
    echo '<div class="error-message center">
          <span class="error-main">Deze pagina bestaat niet.</span>
          <br>
          <span class="error-detail">U wordt terug verwezen naar de homepage.</span>
          </div>';
    ?>
<?php endif; ?>