<?php if (isset($this->pageObj->profileForm)) : ?>
    <div class="zzp-form">
        <?= $this->pageObj->profileForm ?>
    </div>
<?php else : ?>
    <?php
    echo '<div class="error-message center">
          <span class="error-main">Deze pagina bestaat niet.</span>
          <br>
          <span class="error-detail">U wordt terug verwezen naar de homepage.</span>
          </div>';
    ?>
<?php endif; ?>