<div class="container-fluid tasklist">
    <div class="container tasklist-head">
        <h1 class="tasklist-head-text">Opdrachten</h1>
        <hr>
        <form class="tasklist-form" method="post" action="<?= $this->urlArr['baseUrl'] ?>tasklist">
            <div class="form-row">
                <!--Wat invoer-->
                <div class="col-8 col-sm-7">
                    <input type="text" class="form-control mb-2" id="zoek" placeholder="Zoek opdrachten:">
                </div>
                <!--Plaats invoer-->
                <div class="col-4 col-sm-3">
                    <select class="custom-select mb-2" id="locatie">
                        <option selected disabled>Waar:</option>
                        <option value="1">Drenthe</option>
                        <option value="2">Flevoland</option>
                        <option value="3">Friesland</option>
                        <option value="4">Gelderland</option>
                        <option value="5">Groningen</option>
                        <option value="6">Limburg</option>
                        <option value="7">Noord-Brabant</option>
                        <option value="8">Noord-Holland</option>
                        <option value="9">Overrijsel</option>
                        <option value="10">Utrecht</option>
                        <option value="11">Zeeland</option>
                        <option value="12">Zuid-Holland</option>
                    </select>
                </div>
                <!--Zoek button-->
                <div class="col-12 col-sm-2">
                    <button type="submit" class="btn btn-block btn-primary mb-2">Zoeken</button>
                </div>
            </div>
        </form>
    </div>
    <div class="tasklist-content">
        <hr>
        <div class="row">
            <!--Filter balk-->
            <div class="col-12 col-lg-3">
                <div class="tasklist-filter-row">
                    <div class="tasklist-filter-card h-100 card">
                        <div class="card-header">
                            <h3 class="tasklist-title card-title">Filter:</h3>
                        </div>
                        <div class="tasklist-filter-body card-body">
                            <div class="row">
                                <div class="col-12 col-sm-4 col-lg-12">
                                    <label class="tasklist-filter-head" for="tags"><b>Tags:</b></label>
                                    <select class="custom-select mb-2" id="tags">
                                        <option selected disabled>Kies Tags:</option>
                                        <option value="1">Web Development</option>
                                        <option value="2">Schoonmaak</option>
                                        <option value="3">Administratie</option>
                                    </select>
                                </div>
                                <div class="col-12 col-sm-4 col-lg-12">
                                    <label class="tasklist-filter-head" for="locatie"><b>Locatie:</b></label>
                                    <select class="custom-select mb-2" id="locatie">
                                        <option selected disabled>Kies Locaties:</option>
                                        <option value="1">Drenthe</option>
                                        <option value="2">Flevoland</option>
                                        <option value="3">Friesland</option>
                                        <option value="4">Gelderland</option>
                                        <option value="5">Groningen</option>
                                        <option value="6">Limburg</option>
                                        <option value="7">Noord-Brabant</option>
                                        <option value="8">Noord-Holland</option>
                                        <option value="9">Overrijsel</option>
                                        <option value="10">Utrecht</option>
                                        <option value="11">Zeeland</option>
                                        <option value="12">Zuid-Holland</option>
                                    </select>
                                </div>
                                <div class="col-12 col-sm-4 col-lg-12">
                                    <label class="tasklist-filter-head" for="bedrijf"><b>Bedrijf:</b></label>
                                    <select class="custom-select mb-2" id="bedrijf">
                                        <option selected disabled>Kies Bedrijven:</option>
                                        <option value="1">Bakker Bart</option>
                                        <option value="2">Dolfijn.nl</option>
                                        <option value="3">TipTop.org</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-sm-6 col-lg-12">
                                    <label class="tasklist-filter-head" for="UurSlider"><b>Aantal Uren:</b></label>
                                    <input type="range" class="custom-range" min="0" max="500" step="25" id="UurSlider">
                                    <div class="row no-gutters slider-text">
                                        <div class="col-4"><h6 class="text-left">0 uur</h6></div>
                                        <div class="col-4"><h6 class="text-center"><b><span id="UurOutput"></span> uur</b></h6></div>
                                        <div class="col-4"><h6 class="text-right">500 uur</h6></div>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 col-lg-12">
                                    <label class="tasklist-filter-head" for="SalSlider"><b>Uur Salaris:</b></label>
                                    <input type="range" class="custom-range" min="5" max="20" step="0.5" id="SalSlider">
                                    <div class="row no-gutters slider-text">
                                        <div class="col-4"><h6 class="text-left">€5/uur</h6></div>
                                        <div class="col-4"><h6 class="text-center"><b>€<span id="SalOutput"></span>/uur</b></h6></div>
                                        <div class="col-4"><h6 class="text-right">€20/uur</h6></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--Opdracht cards-->
            <div class="col-12 col-lg-9 tasklist-body-row">
                <hr class="filter-row">
                <div class="tasklist-body">
                    <!--task items-->
                </div>
            </div>
        </div>
    </div>
</div>