<div class="container task">
    <h1 class="task-head-text">Opdracht</h1>
    <hr>
    <div class="row">
        <div class="col-6">
            <img class="task-img img-fluid" src="../img/task-img/coding.jpg" alt="task img">
        </div>
        <div class="col-6">

        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <?= $taskitems ?>
        </div>
    </div>
</div>